
server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://47.98.180.20:3306/s-tech?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: stkdb
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10000000000
      max-request-size: 10000000000
      location: /data/upload_tmp

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


path:
  upload:
    folder: /home/
  prefix:
    folder: files/
    url: http://47.98.180.20/

